### ISSUE TITLE
shell flag not working with fish

### ISSUE THREAD

**Issue by Arkaeriit** [nate-sys/muc#21]
The `shell` args with fish as its value does not help parse a fish history. I could try to fix it later today or tomorrow.

```
^[n.n]^ ~/Dev/rust/muc >HISTFILE=~/.local/share/fish/fish_history target/debug/muc --file $HIST
FILE --count 10 --prefix="- cmd: " --pretty
[▮▮▮▮▮▮▮▮▮▮]  8.13% 188 cd 
[▮▮▮▮▮▮▮▮  ]  6.75% 156 vim 
[▮▮▮▮▮▮▮   ]  5.75% 133 git 
[▮▮▮▮▮▮    ]  5.58% 129 ls 
[▮▮▮▮▮▮    ]  5.23% 121 sudo 
[▮▮▮▮▮     ]  4.54% 105 mv 
[▮▮▮▮      ]  4.02%  93 aria2c 
[▮▮▮       ]  3.03%  70 cat 
[▮▮▮       ]  2.98%  69 rm 
[▮▮        ]  1.82%  42 mkdir 
 ...  1206 (~52%) others 
^[n.n]^ ~/Dev/rust/muc >HISTFILE=~/.local/share/fish/fish_history target/debug/muc --file $HIST
FILE --count 10 --shell fish --pretty
[▮▮▮▮▮▮▮▮▮▮] 24.00% 2392 when 
[▮▮▮▮▮     ] 13.16% 1311 - 
[▮▮▮▮      ] 11.46% 1142 paths 
[          ]  2.26%  225 cd 
[          ]  1.90%  189 vim 
[          ]  1.63%  162 ls 
[          ]  1.54%  153 git 
[          ]  1.44%  143 sudo 
[          ]  1.24%  124 mv 
[          ]  0.93%   93 aria2c 
 ...  4031 (~40%) others 
```

**Comment by anemovva** [comment]
Can you send a few example likes from your history file?

**Comment by Arkaeriit** [comment]
The output I send are made with my history file. In the current state of the code (`cd06b6f`), the fish flag only removes the `- cmd: ` prefix to each command, but it doesn't filter out the metadata that are around the commands. Here is an example of a fish history file:

```
- cmd: cd dev/perso/muc/
  when: 1672332425
  paths:
    - dev/perso/muc/
- cmd: git branch
  when: 1672332427
- cmd: git co -b swifter_unquoting
  when: 1672332443
- cmd: vim src/hist_file.rs
  when: 1672332446
```

As you can see, a lot of lines are not commands.
